# Generated by Django 5.2.8 on 2025-12-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField(blank=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('banca', models.CharField(max_length=100)),
                ('imagem_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='organizador',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
